apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot-deployment-prod
  namespace: prod
  labels:
    app: polybot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot
  template:
    metadata:
        labels:
          app: polybot
    spec:
      containers:
      - name: server
        image: ehab215/polybot_prod:v1.0.63
        ports:
        - containerPort: 8443 # Ensure this matches your application's listening port
        env:
          - name: secret_name
            value: ehabo_telegram_tokenV1_tf
          - name: TELEGRAM_APP_URL
            value: https://ehabo-polybot-k8s-v1.int-devops.click
          - name: REGION_NAME
            value: eu-west-3
          - name: SQS_QUEUE_URL
            value: https://sqs.eu-west-3.amazonaws.com/019273956931/ehabo-PolybotServiceQueue-k8s
        volumeMounts:
          - name: tls-vol
            mountPath: /usr/src/app/tls
      volumes:
        - name: tls-vol
          secret:
            secretName: polybot-tls
            items:
             - key: tls.crt
               path: cert
             - key: tls.key
               path: key

---
apiVersion: v1
kind: Service
metadata:
  name: polybot-service-1
  namespace: prod
spec:
  selector:
    app: polybot
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443